# Pytzer: Pitzer model for chemical activities in aqueous solutions.
# Copyright (C) 2019--2020  Matthew Paul Humphreys  (GNU GPLv3)
from .. import parameters as prm
from .. import debyehueckel, unsymmetrical

name = "HMW84"
plname.update_Aphi(debyehueckel.Aosm_M88)
plname.assign_func_J(unsymmetrical.Harvie)
bC = {}
plname.update_ca("Na", "Cl", prm.bC_Na_Cl_HMW84)
plname.update_ca("Na", "SO4", prm.bC_Na_SO4_HMW84)
plname.update_ca("Na", "HSO4", prm.bC_Na_HSO4_HMW84)
plname.update_ca("Na", "OH", prm.bC_Na_OH_HMW84)
plname.update_ca("Na", "HCO3", prm.bC_Na_HCO3_HMW84)
plname.update_ca("Na", "CO3", prm.bC_Na_CO3_HMW84)
plname.update_ca("K", "Cl", prm.bC_K_Cl_HMW84)
plname.update_ca("K", "SO4", prm.bC_K_SO4_HMW84)
plname.update_ca("K", "HSO4", prm.bC_K_HSO4_HMW84)
plname.update_ca("K", "OH", prm.bC_K_OH_HMW84)
plname.update_ca("K", "HCO3", prm.bC_K_HCO3_HMW84)
plname.update_ca("K", "CO3", prm.bC_K_CO3_HMW84)
plname.update_ca("Ca", "Cl", prm.bC_Ca_Cl_HMW84)
plname.update_ca("Ca", "SO4", prm.bC_Ca_SO4_HMW84)
plname.update_ca("Ca", "HSO4", prm.bC_Ca_HSO4_HMW84)
plname.update_ca("Ca", "OH", prm.bC_Ca_OH_HMW84)
plname.update_ca("Ca", "HCO3", prm.bC_Ca_HCO3_HMW84)
plname.update_ca("Ca", "CO3", prm.bC_Ca_CO3_HMW84)
plname.update_ca("Mg", "Cl", prm.bC_Mg_Cl_HMW84)
plname.update_ca("Mg", "SO4", prm.bC_Mg_SO4_HMW84)
plname.update_ca("Mg", "HSO4", prm.bC_Mg_HSO4_HMW84)
plname.update_ca("Mg", "OH", prm.bC_Mg_OH_HMW84)
plname.update_ca("Mg", "HCO3", prm.bC_Mg_HCO3_HMW84)
plname.update_ca("Mg", "CO3", prm.bC_Mg_CO3_HMW84)
plname.update_ca("MgOH", "Cl", prm.bC_MgOH_Cl_HMW84)
plname.update_ca("MgOH", "SO4", prm.bC_MgOH_SO4_HMW84)
plname.update_ca("MgOH", "HSO4", prm.bC_MgOH_HSO4_HMW84)
plname.update_ca("MgOH", "OH", prm.bC_MgOH_OH_HMW84)
plname.update_ca("MgOH", "HCO3", prm.bC_MgOH_HCO3_HMW84)
plname.update_ca("MgOH", "CO3", prm.bC_MgOH_CO3_HMW84)
plname.update_ca("H", "Cl", prm.bC_H_Cl_HMW84)
plname.update_ca("H", "SO4", prm.bC_H_SO4_HMW84)
plname.update_ca("H", "HSO4", prm.bC_H_HSO4_HMW84)
plname.update_ca("H", "OH", prm.bC_H_OH_HMW84)
plname.update_ca("H", "HCO3", prm.bC_H_HCO3_HMW84)
plname.update_ca("H", "CO3", prm.bC_H_CO3_HMW84)
theta = {}
psi = {}
plname.update_xx("Cl", "SO4", prm.theta_Cl_SO4_HMW84)
plname.update_cxa("Na", "Cl", "SO4", prm.psi_Na_Cl_SO4_HMW84)
plname.update_cxa("K", "Cl", "SO4", prm.psi_K_Cl_SO4_HMW84)
plname.update_cxa("Ca", "Cl", "SO4", prm.psi_Ca_Cl_SO4_HMW84)
plname.update_cxa("Mg", "Cl", "SO4", prm.psi_Mg_Cl_SO4_HMW84)
plname.update_cxa("MgOH", "Cl", "SO4", prm.psi_MgOH_Cl_SO4_HMW84)
plname.update_cxa("H", "Cl", "SO4", prm.psi_H_Cl_SO4_HMW84)
plname.update_xx("Cl", "HSO4", prm.theta_Cl_HSO4_HMW84)
plname.update_cxa("Na", "Cl", "HSO4", prm.psi_Na_Cl_HSO4_HMW84)
plname.update_cxa("K", "Cl", "HSO4", prm.psi_K_Cl_HSO4_HMW84)
plname.update_cxa("Ca", "Cl", "HSO4", prm.psi_Ca_Cl_HSO4_HMW84)
plname.update_cxa("Mg", "Cl", "HSO4", prm.psi_Mg_Cl_HSO4_HMW84)
plname.update_cxa("MgOH", "Cl", "HSO4", prm.psi_MgOH_Cl_HSO4_HMW84)
plname.update_cxa("H", "Cl", "HSO4", prm.psi_H_Cl_HSO4_HMW84)
plname.update_xx("Cl", "OH", prm.theta_Cl_OH_HMW84)
plname.update_cxa("Na", "Cl", "OH", prm.psi_Na_Cl_OH_HMW84)
plname.update_cxa("K", "Cl", "OH", prm.psi_K_Cl_OH_HMW84)
plname.update_cxa("Ca", "Cl", "OH", prm.psi_Ca_Cl_OH_HMW84)
plname.update_cxa("Mg", "Cl", "OH", prm.psi_Mg_Cl_OH_HMW84)
plname.update_cxa("MgOH", "Cl", "OH", prm.psi_MgOH_Cl_OH_HMW84)
plname.update_cxa("H", "Cl", "OH", prm.psi_H_Cl_OH_HMW84)
plname.update_xx("Cl", "HCO3", prm.theta_Cl_HCO3_HMW84)
plname.update_cxa("Na", "Cl", "HCO3", prm.psi_Na_Cl_HCO3_HMW84)
plname.update_cxa("K", "Cl", "HCO3", prm.psi_K_Cl_HCO3_HMW84)
plname.update_cxa("Ca", "Cl", "HCO3", prm.psi_Ca_Cl_HCO3_HMW84)
plname.update_cxa("Mg", "Cl", "HCO3", prm.psi_Mg_Cl_HCO3_HMW84)
plname.update_cxa("MgOH", "Cl", "HCO3", prm.psi_MgOH_Cl_HCO3_HMW84)
plname.update_cxa("H", "Cl", "HCO3", prm.psi_H_Cl_HCO3_HMW84)
plname.update_xx("CO3", "Cl", prm.theta_CO3_Cl_HMW84)
plname.update_cxa("Na", "CO3", "Cl", prm.psi_Na_CO3_Cl_HMW84)
plname.update_cxa("K", "CO3", "Cl", prm.psi_K_CO3_Cl_HMW84)
plname.update_cxa("Ca", "CO3", "Cl", prm.psi_Ca_CO3_Cl_HMW84)
plname.update_cxa("Mg", "CO3", "Cl", prm.psi_Mg_CO3_Cl_HMW84)
plname.update_cxa("MgOH", "CO3", "Cl", prm.psi_MgOH_CO3_Cl_HMW84)
plname.update_cxa("H", "CO3", "Cl", prm.psi_H_CO3_Cl_HMW84)
plname.update_xx("HSO4", "SO4", prm.theta_HSO4_SO4_HMW84)
plname.update_cxa("Na", "HSO4", "SO4", prm.psi_Na_HSO4_SO4_HMW84)
plname.update_cxa("K", "HSO4", "SO4", prm.psi_K_HSO4_SO4_HMW84)
plname.update_cxa("Ca", "HSO4", "SO4", prm.psi_Ca_HSO4_SO4_HMW84)
plname.update_cxa("Mg", "HSO4", "SO4", prm.psi_Mg_HSO4_SO4_HMW84)
plname.update_cxa("MgOH", "HSO4", "SO4", prm.psi_MgOH_HSO4_SO4_HMW84)
plname.update_cxa("H", "HSO4", "SO4", prm.psi_H_HSO4_SO4_HMW84)
plname.update_xx("OH", "SO4", prm.theta_OH_SO4_HMW84)
plname.update_cxa("Na", "OH", "SO4", prm.psi_Na_OH_SO4_HMW84)
plname.update_cxa("K", "OH", "SO4", prm.psi_K_OH_SO4_HMW84)
plname.update_cxa("Ca", "OH", "SO4", prm.psi_Ca_OH_SO4_HMW84)
plname.update_cxa("Mg", "OH", "SO4", prm.psi_Mg_OH_SO4_HMW84)
plname.update_cxa("MgOH", "OH", "SO4", prm.psi_MgOH_OH_SO4_HMW84)
plname.update_cxa("H", "OH", "SO4", prm.psi_H_OH_SO4_HMW84)
plname.update_xx("HCO3", "SO4", prm.theta_HCO3_SO4_HMW84)
plname.update_cxa("Na", "HCO3", "SO4", prm.psi_Na_HCO3_SO4_HMW84)
plname.update_cxa("K", "HCO3", "SO4", prm.psi_K_HCO3_SO4_HMW84)
plname.update_cxa("Ca", "HCO3", "SO4", prm.psi_Ca_HCO3_SO4_HMW84)
plname.update_cxa("Mg", "HCO3", "SO4", prm.psi_Mg_HCO3_SO4_HMW84)
plname.update_cxa("MgOH", "HCO3", "SO4", prm.psi_MgOH_HCO3_SO4_HMW84)
plname.update_cxa("H", "HCO3", "SO4", prm.psi_H_HCO3_SO4_HMW84)
plname.update_xx("CO3", "SO4", prm.theta_CO3_SO4_HMW84)
plname.update_cxa("Na", "CO3", "SO4", prm.psi_Na_CO3_SO4_HMW84)
plname.update_cxa("K", "CO3", "SO4", prm.psi_K_CO3_SO4_HMW84)
plname.update_cxa("Ca", "CO3", "SO4", prm.psi_Ca_CO3_SO4_HMW84)
plname.update_cxa("Mg", "CO3", "SO4", prm.psi_Mg_CO3_SO4_HMW84)
plname.update_cxa("MgOH", "CO3", "SO4", prm.psi_MgOH_CO3_SO4_HMW84)
plname.update_cxa("H", "CO3", "SO4", prm.psi_H_CO3_SO4_HMW84)
plname.update_xx("HSO4", "OH", prm.theta_HSO4_OH_HMW84)
plname.update_cxa("Na", "HSO4", "OH", prm.psi_Na_HSO4_OH_HMW84)
plname.update_cxa("K", "HSO4", "OH", prm.psi_K_HSO4_OH_HMW84)
plname.update_cxa("Ca", "HSO4", "OH", prm.psi_Ca_HSO4_OH_HMW84)
plname.update_cxa("Mg", "HSO4", "OH", prm.psi_Mg_HSO4_OH_HMW84)
plname.update_cxa("MgOH", "HSO4", "OH", prm.psi_MgOH_HSO4_OH_HMW84)
plname.update_cxa("H", "HSO4", "OH", prm.psi_H_HSO4_OH_HMW84)
plname.update_xx("HCO3", "HSO4", prm.theta_HCO3_HSO4_HMW84)
plname.update_cxa("Na", "HCO3", "HSO4", prm.psi_Na_HCO3_HSO4_HMW84)
plname.update_cxa("K", "HCO3", "HSO4", prm.psi_K_HCO3_HSO4_HMW84)
plname.update_cxa("Ca", "HCO3", "HSO4", prm.psi_Ca_HCO3_HSO4_HMW84)
plname.update_cxa("Mg", "HCO3", "HSO4", prm.psi_Mg_HCO3_HSO4_HMW84)
plname.update_cxa("MgOH", "HCO3", "HSO4", prm.psi_MgOH_HCO3_HSO4_HMW84)
plname.update_cxa("H", "HCO3", "HSO4", prm.psi_H_HCO3_HSO4_HMW84)
plname.update_xx("CO3", "HSO4", prm.theta_CO3_HSO4_HMW84)
plname.update_cxa("Na", "CO3", "HSO4", prm.psi_Na_CO3_HSO4_HMW84)
plname.update_cxa("K", "CO3", "HSO4", prm.psi_K_CO3_HSO4_HMW84)
plname.update_cxa("Ca", "CO3", "HSO4", prm.psi_Ca_CO3_HSO4_HMW84)
plname.update_cxa("Mg", "CO3", "HSO4", prm.psi_Mg_CO3_HSO4_HMW84)
plname.update_cxa("MgOH", "CO3", "HSO4", prm.psi_MgOH_CO3_HSO4_HMW84)
plname.update_cxa("H", "CO3", "HSO4", prm.psi_H_CO3_HSO4_HMW84)
plname.update_xx("HCO3", "OH", prm.theta_HCO3_OH_HMW84)
plname.update_cxa("Na", "HCO3", "OH", prm.psi_Na_HCO3_OH_HMW84)
plname.update_cxa("K", "HCO3", "OH", prm.psi_K_HCO3_OH_HMW84)
plname.update_cxa("Ca", "HCO3", "OH", prm.psi_Ca_HCO3_OH_HMW84)
plname.update_cxa("Mg", "HCO3", "OH", prm.psi_Mg_HCO3_OH_HMW84)
plname.update_cxa("MgOH", "HCO3", "OH", prm.psi_MgOH_HCO3_OH_HMW84)
plname.update_cxa("H", "HCO3", "OH", prm.psi_H_HCO3_OH_HMW84)
plname.update_xx("CO3", "OH", prm.theta_CO3_OH_HMW84)
plname.update_cxa("Na", "CO3", "OH", prm.psi_Na_CO3_OH_HMW84)
plname.update_cxa("K", "CO3", "OH", prm.psi_K_CO3_OH_HMW84)
plname.update_cxa("Ca", "CO3", "OH", prm.psi_Ca_CO3_OH_HMW84)
plname.update_cxa("Mg", "CO3", "OH", prm.psi_Mg_CO3_OH_HMW84)
plname.update_cxa("MgOH", "CO3", "OH", prm.psi_MgOH_CO3_OH_HMW84)
plname.update_cxa("H", "CO3", "OH", prm.psi_H_CO3_OH_HMW84)
plname.update_xx("CO3", "HCO3", prm.theta_CO3_HCO3_HMW84)
plname.update_cxa("Na", "CO3", "HCO3", prm.psi_Na_CO3_HCO3_HMW84)
plname.update_cxa("K", "CO3", "HCO3", prm.psi_K_CO3_HCO3_HMW84)
plname.update_cxa("Ca", "CO3", "HCO3", prm.psi_Ca_CO3_HCO3_HMW84)
plname.update_cxa("Mg", "CO3", "HCO3", prm.psi_Mg_CO3_HCO3_HMW84)
plname.update_cxa("MgOH", "CO3", "HCO3", prm.psi_MgOH_CO3_HCO3_HMW84)
plname.update_cxa("H", "CO3", "HCO3", prm.psi_H_CO3_HCO3_HMW84)
plname.update_xx("K", "Na", prm.theta_K_Na_HMW84)
plname.update_cxa("K", "Na", "Cl", prm.psi_K_Na_Cl_HMW84)
plname.update_cxa("K", "Na", "SO4", prm.psi_K_Na_SO4_HMW84)
plname.update_cxa("K", "Na", "HSO4", prm.psi_K_Na_HSO4_HMW84)
plname.update_cxa("K", "Na", "OH", prm.psi_K_Na_OH_HMW84)
plname.update_cxa("K", "Na", "HCO3", prm.psi_K_Na_HCO3_HMW84)
plname.update_cxa("K", "Na", "CO3", prm.psi_K_Na_CO3_HMW84)
plname.update_xx("Ca", "Na", prm.theta_Ca_Na_HMW84)
plname.update_cxa("Ca", "Na", "Cl", prm.psi_Ca_Na_Cl_HMW84)
plname.update_cxa("Ca", "Na", "SO4", prm.psi_Ca_Na_SO4_HMW84)
plname.update_cxa("Ca", "Na", "HSO4", prm.psi_Ca_Na_HSO4_HMW84)
plname.update_cxa("Ca", "Na", "OH", prm.psi_Ca_Na_OH_HMW84)
plname.update_cxa("Ca", "Na", "HCO3", prm.psi_Ca_Na_HCO3_HMW84)
plname.update_cxa("Ca", "Na", "CO3", prm.psi_Ca_Na_CO3_HMW84)
plname.update_xx("Mg", "Na", prm.theta_Mg_Na_HMW84)
plname.update_cxa("Mg", "Na", "Cl", prm.psi_Mg_Na_Cl_HMW84)
plname.update_cxa("Mg", "Na", "SO4", prm.psi_Mg_Na_SO4_HMW84)
plname.update_cxa("Mg", "Na", "HSO4", prm.psi_Mg_Na_HSO4_HMW84)
plname.update_cxa("Mg", "Na", "OH", prm.psi_Mg_Na_OH_HMW84)
plname.update_cxa("Mg", "Na", "HCO3", prm.psi_Mg_Na_HCO3_HMW84)
plname.update_cxa("Mg", "Na", "CO3", prm.psi_Mg_Na_CO3_HMW84)
plname.update_xx("MgOH", "Na", prm.theta_MgOH_Na_HMW84)
plname.update_cxa("MgOH", "Na", "Cl", prm.psi_MgOH_Na_Cl_HMW84)
plname.update_cxa("MgOH", "Na", "SO4", prm.psi_MgOH_Na_SO4_HMW84)
plname.update_cxa("MgOH", "Na", "HSO4", prm.psi_MgOH_Na_HSO4_HMW84)
plname.update_cxa("MgOH", "Na", "OH", prm.psi_MgOH_Na_OH_HMW84)
plname.update_cxa("MgOH", "Na", "HCO3", prm.psi_MgOH_Na_HCO3_HMW84)
plname.update_cxa("MgOH", "Na", "CO3", prm.psi_MgOH_Na_CO3_HMW84)
plname.update_xx("H", "Na", prm.theta_H_Na_HMW84)
plname.update_cxa("H", "Na", "Cl", prm.psi_H_Na_Cl_HMW84)
plname.update_cxa("H", "Na", "SO4", prm.psi_H_Na_SO4_HMW84)
plname.update_cxa("H", "Na", "HSO4", prm.psi_H_Na_HSO4_HMW84)
plname.update_cxa("H", "Na", "OH", prm.psi_H_Na_OH_HMW84)
plname.update_cxa("H", "Na", "HCO3", prm.psi_H_Na_HCO3_HMW84)
plname.update_cxa("H", "Na", "CO3", prm.psi_H_Na_CO3_HMW84)
plname.update_xx("Ca", "K", prm.theta_Ca_K_HMW84)
plname.update_cxa("Ca", "K", "Cl", prm.psi_Ca_K_Cl_HMW84)
plname.update_cxa("Ca", "K", "SO4", prm.psi_Ca_K_SO4_HMW84)
plname.update_cxa("Ca", "K", "HSO4", prm.psi_Ca_K_HSO4_HMW84)
plname.update_cxa("Ca", "K", "OH", prm.psi_Ca_K_OH_HMW84)
plname.update_cxa("Ca", "K", "HCO3", prm.psi_Ca_K_HCO3_HMW84)
plname.update_cxa("Ca", "K", "CO3", prm.psi_Ca_K_CO3_HMW84)
plname.update_xx("K", "Mg", prm.theta_K_Mg_HMW84)
plname.update_cxa("K", "Mg", "Cl", prm.psi_K_Mg_Cl_HMW84)
plname.update_cxa("K", "Mg", "SO4", prm.psi_K_Mg_SO4_HMW84)
plname.update_cxa("K", "Mg", "HSO4", prm.psi_K_Mg_HSO4_HMW84)
plname.update_cxa("K", "Mg", "OH", prm.psi_K_Mg_OH_HMW84)
plname.update_cxa("K", "Mg", "HCO3", prm.psi_K_Mg_HCO3_HMW84)
plname.update_cxa("K", "Mg", "CO3", prm.psi_K_Mg_CO3_HMW84)
plname.update_xx("K", "MgOH", prm.theta_K_MgOH_HMW84)
plname.update_cxa("K", "MgOH", "Cl", prm.psi_K_MgOH_Cl_HMW84)
plname.update_cxa("K", "MgOH", "SO4", prm.psi_K_MgOH_SO4_HMW84)
plname.update_cxa("K", "MgOH", "HSO4", prm.psi_K_MgOH_HSO4_HMW84)
plname.update_cxa("K", "MgOH", "OH", prm.psi_K_MgOH_OH_HMW84)
plname.update_cxa("K", "MgOH", "HCO3", prm.psi_K_MgOH_HCO3_HMW84)
plname.update_cxa("K", "MgOH", "CO3", prm.psi_K_MgOH_CO3_HMW84)
plname.update_xx("H", "K", prm.theta_H_K_HMW84)
plname.update_cxa("H", "K", "Cl", prm.psi_H_K_Cl_HMW84)
plname.update_cxa("H", "K", "SO4", prm.psi_H_K_SO4_HMW84)
plname.update_cxa("H", "K", "HSO4", prm.psi_H_K_HSO4_HMW84)
plname.update_cxa("H", "K", "OH", prm.psi_H_K_OH_HMW84)
plname.update_cxa("H", "K", "HCO3", prm.psi_H_K_HCO3_HMW84)
plname.update_cxa("H", "K", "CO3", prm.psi_H_K_CO3_HMW84)
plname.update_xx("Ca", "Mg", prm.theta_Ca_Mg_HMW84)
plname.update_cxa("Ca", "Mg", "Cl", prm.psi_Ca_Mg_Cl_HMW84)
plname.update_cxa("Ca", "Mg", "SO4", prm.psi_Ca_Mg_SO4_HMW84)
plname.update_cxa("Ca", "Mg", "HSO4", prm.psi_Ca_Mg_HSO4_HMW84)
plname.update_cxa("Ca", "Mg", "OH", prm.psi_Ca_Mg_OH_HMW84)
plname.update_cxa("Ca", "Mg", "HCO3", prm.psi_Ca_Mg_HCO3_HMW84)
plname.update_cxa("Ca", "Mg", "CO3", prm.psi_Ca_Mg_CO3_HMW84)
plname.update_xx("Ca", "MgOH", prm.theta_Ca_MgOH_HMW84)
plname.update_cxa("Ca", "MgOH", "Cl", prm.psi_Ca_MgOH_Cl_HMW84)
plname.update_cxa("Ca", "MgOH", "SO4", prm.psi_Ca_MgOH_SO4_HMW84)
plname.update_cxa("Ca", "MgOH", "HSO4", prm.psi_Ca_MgOH_HSO4_HMW84)
plname.update_cxa("Ca", "MgOH", "OH", prm.psi_Ca_MgOH_OH_HMW84)
plname.update_cxa("Ca", "MgOH", "HCO3", prm.psi_Ca_MgOH_HCO3_HMW84)
plname.update_cxa("Ca", "MgOH", "CO3", prm.psi_Ca_MgOH_CO3_HMW84)
plname.update_xx("Ca", "H", prm.theta_Ca_H_HMW84)
plname.update_cxa("Ca", "H", "Cl", prm.psi_Ca_H_Cl_HMW84)
plname.update_cxa("Ca", "H", "SO4", prm.psi_Ca_H_SO4_HMW84)
plname.update_cxa("Ca", "H", "HSO4", prm.psi_Ca_H_HSO4_HMW84)
plname.update_cxa("Ca", "H", "OH", prm.psi_Ca_H_OH_HMW84)
plname.update_cxa("Ca", "H", "HCO3", prm.psi_Ca_H_HCO3_HMW84)
plname.update_cxa("Ca", "H", "CO3", prm.psi_Ca_H_CO3_HMW84)
plname.update_xx("Mg", "MgOH", prm.theta_Mg_MgOH_HMW84)
plname.update_cxa("Mg", "MgOH", "Cl", prm.psi_Mg_MgOH_Cl_HMW84)
plname.update_cxa("Mg", "MgOH", "SO4", prm.psi_Mg_MgOH_SO4_HMW84)
plname.update_cxa("Mg", "MgOH", "HSO4", prm.psi_Mg_MgOH_HSO4_HMW84)
plname.update_cxa("Mg", "MgOH", "OH", prm.psi_Mg_MgOH_OH_HMW84)
plname.update_cxa("Mg", "MgOH", "HCO3", prm.psi_Mg_MgOH_HCO3_HMW84)
plname.update_cxa("Mg", "MgOH", "CO3", prm.psi_Mg_MgOH_CO3_HMW84)
plname.update_xx("H", "Mg", prm.theta_H_Mg_HMW84)
plname.update_cxa("H", "Mg", "Cl", prm.psi_H_Mg_Cl_HMW84)
plname.update_cxa("H", "Mg", "SO4", prm.psi_H_Mg_SO4_HMW84)
plname.update_cxa("H", "Mg", "HSO4", prm.psi_H_Mg_HSO4_HMW84)
plname.update_cxa("H", "Mg", "OH", prm.psi_H_Mg_OH_HMW84)
plname.update_cxa("H", "Mg", "HCO3", prm.psi_H_Mg_HCO3_HMW84)
plname.update_cxa("H", "Mg", "CO3", prm.psi_H_Mg_CO3_HMW84)
plname.update_xx("H", "MgOH", prm.theta_H_MgOH_HMW84)
plname.update_cxa("H", "MgOH", "Cl", prm.psi_H_MgOH_Cl_HMW84)
plname.update_cxa("H", "MgOH", "SO4", prm.psi_H_MgOH_SO4_HMW84)
plname.update_cxa("H", "MgOH", "HSO4", prm.psi_H_MgOH_HSO4_HMW84)
plname.update_cxa("H", "MgOH", "OH", prm.psi_H_MgOH_OH_HMW84)
plname.update_cxa("H", "MgOH", "HCO3", prm.psi_H_MgOH_HCO3_HMW84)
plname.update_cxa("H", "MgOH", "CO3", prm.psi_H_MgOH_CO3_HMW84)
lambd = {}
lambd["CO2_H"] = prm.lambd_CO2_H_HMW84
lambd["CO2_Na"] = prm.lambd_CO2_Na_HMW84
lambd["CO2_K"] = prm.lambd_CO2_K_HMW84
lambd["CO2_Ca"] = prm.lambd_CO2_Ca_HMW84
lambd["CO2_Mg"] = prm.lambd_CO2_Mg_HMW84
lambd["CO2_Cl"] = prm.lambd_CO2_Cl_HMW84
lambd["CO2_SO4"] = prm.lambd_CO2_SO4_HMW84
lambd["CO2_HSO4"] = prm.lambd_CO2_HSO4_HMW84
